"""
IBM DAPC - Course 04
Module 05 - APIs and Data Collection

Lab 03 - API Examples

01_IBM_Lab.py

Purpose:
Practice working with API-generated user data using
the RandomUser package and Pandas.
"""

# =========================================================
# 1. Import Libraries
# =========================================================

from randomuser import RandomUser
import pandas as pd


# =========================================================
# 2. Generate Random Users
# =========================================================

users = RandomUser.generate_users(10)

print("Number of Users Generated:")
print(len(users))


# =========================================================
# 3. Inspect One User
# =========================================================

print("\nFirst User:")
print(users[0])


# =========================================================
# 4. Extract User Information
# =========================================================

user_data = []

for user in users:

    user_data.append(
        {
            "Name": user.get_full_name(),
            "Gender": user.get_gender(),
            "City": user.get_city(),
            "State": user.get_state(),
            "Email": user.get_email(),
            "DOB": user.get_dob(),
            "Picture": user.get_picture()
        }
    )


# =========================================================
# 5. Convert to Pandas DataFrame
# =========================================================

df = pd.DataFrame(user_data)


# =========================================================
# 6. Display DataFrame
# =========================================================

print("\nUser DataFrame:")
print(df)


# =========================================================
# 7. Display DataFrame Information
# =========================================================

print("\nDataFrame Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())


# =========================================================
# 8. IBM-Style Function
# =========================================================

def get_users():

    users = []

    for user in RandomUser.generate_users(10):

        users.append(
            {
                "Name": user.get_full_name(),
                "Gender": user.get_gender(),
                "City": user.get_city(),
                "State": user.get_state(),
                "Email": user.get_email(),
                "DOB": user.get_dob(),
                "Picture": user.get_picture()
            }
        )

    return pd.DataFrame(users)


# =========================================================
# 9. Test get_users() Function
# =========================================================

users_df = get_users()

print("\nDataFrame Generated by get_users():")
print(users_df)


# =========================================================
# 10. Final Summary
# =========================================================

print("\n" + "=" * 60)
print("IBM API EXAMPLES LAB COMPLETED")
print("=" * 60)

print("Records generated:", len(users_df))
print("Columns:", users_df.columns.tolist())